### ISSUE TITLE
unnecessary style for card

### ISSUE THREAD

**Issue by weblancaster** [mrjlancaster/Blog#2]
Pare de copiar sem entender pq vc esta usando algo.

Esse codigo que mui (material ui) usa é para os exemplos no site deles apenas.
https://github.com/mrjlancaster/Blog/blob/c3110053c9699c75c7360f03dd05c8ec8cc7296f/my-blog/src/App.js#L22

**Comment by mrjlancaster** [comment]
eu sei. nao estou compiando. Ontem eu estava  organizando os components, criando new files a importando tudo pros components certos e esqueci de deletar esses do app component.
